# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  -
    binary: super_hooks
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/frankywahl/super_hooks/version.GitRevision={{.FullCommit}} -X github.com/frankywahl/super_hooks/version.Version={{.Version}}
archives:
-
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32bit
    amd64: 64bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
-
  name: super_hooks
  folder: Formula
  homepage: "http://github.com/frankywahl/super_hooks"
  description: "Hooks handling for git"
  github:
    owner: frankywahl
    name: homebrew-tap
